<?php

declare(strict_types=1);

namespace WPRC\Catalog\RobotModel\WordPress;

use WP_Post;
use WP_Term;

defined('ABSPATH') || exit;

/**
 * Builds canonical robot-model permalinks and installs deterministic single
 * rewrite rules.
 *
 * Robot models use a deep editorial URL containing the brand and the complete
 * family / series hierarchy. These path segments are informative only: the
 * final post slug is the identity used to resolve the CPT.
 *
 * Polylang can prepend a language directory to rewrite rules. Rather than
 * relying on capture-group rewriting from a third-party filter, Catalog adds
 * its final localized rules after WordPress and Polylang have generated their
 * own rule sets. This keeps the model slug at $matches[1] whatever the active
 * Polylang URL mode is.
 */
final class Permalinks
{
    private const REWRITE_VERSION = '1.6.0-alpha4';
    private const OPTION = 'wprc_catalog_robot_model_rewrite_version';

    public function registerHooks(): void
    {
        add_filter('post_type_link', [$this, 'filterLink'], 20, 4);

        // Run after Polylang and the WooCommerce catalog rewrite layer. The
        // robot-model single rules must have final priority over broader
        // catalog/taxonomy rules sharing the /robots/ namespace.
        add_filter('rewrite_rules_array', [$this, 'prependFinalRules'], 999);

        // Polylang prepares its rewrite filters on wp_loaded. Flushing earlier
        // (for example on init) can persist a rule set generated without the
        // language routing layer. Flush only after WordPress is fully loaded.
        add_action('wp_loaded', [$this, 'maybeFlush'], 100);
    }

    public function filterLink(string $permalink, WP_Post $post, bool $leaveName, bool $sample): string
    {
        unset($leaveName, $sample);
        if ($post->post_type !== ContentTypes::POST_TYPE) {
            return $permalink;
        }

        $base = home_url('/robots/modeles/');
        if (function_exists('pll_home_url')) {
            $language = function_exists('pll_get_post_language') ? pll_get_post_language($post->ID, 'slug') : null;
            $localizedHome = is_string($language) && $language !== '' ? pll_home_url($language) : null;
            if (is_string($localizedHome) && $localizedHome !== '') {
                $base = trailingslashit($localizedHome) . 'robots/modeles/';
            }
        }

        $segments = [];
        $brands = get_the_terms($post->ID, 'product_brand');
        if (is_array($brands) && isset($brands[0]) && $brands[0] instanceof WP_Term) {
            $segments[] = $brands[0]->slug;
        }

        $family = $this->deepestFamily($post->ID);
        if ($family instanceof WP_Term) {
            $ids = array_reverse(get_ancestors($family->term_id, ContentTypes::FAMILY_TAXONOMY, 'taxonomy'));
            $ids[] = $family->term_id;
            foreach ($ids as $id) {
                $term = get_term((int) $id, ContentTypes::FAMILY_TAXONOMY);
                if ($term instanceof WP_Term && $term->slug !== '') {
                    $segments[] = $term->slug;
                }
            }
        }

        $segments[] = $post->post_name !== '' ? $post->post_name : '%postname%';
        return trailingslashit($base . implode('/', array_filter($segments)));
    }

    /**
     * Prepend the final single-model rules after all regular rewrite generation.
     *
     * @param array<string,string> $rules
     * @return array<string,string>
     */
    public function prependFinalRules(array $rules): array
    {
        $base = preg_quote($this->archiveSlug(), '#');
        $customRules = [];

        foreach ($this->localizedPrefixes() as $entry) {
            $prefix = $entry['prefix'] !== '' ? preg_quote($entry['prefix'], '#') . '/' : '';
            $queryPrefix = 'index.php?post_type=' . ContentTypes::POST_TYPE . '&' . ContentTypes::POST_TYPE . '=$matches[1]';

            // In directory mode the language is deterministic from the literal
            // prefix and can be passed explicitly. In domain/no-prefix mode the
            // host/current request remains responsible for language detection.
            if ($entry['prefix'] !== '' && $entry['language'] !== '') {
                $queryPrefix .= '&lang=' . rawurlencode($entry['language']);
            }

            $reserved = '(?!famille(?:/|$)|page(?:/|$)|feed(?:/|$)|embed/?$)';

            // Hierarchical canonical URL, e.g.
            // /fr/robots/modeles/kuka/kr-quantec/kr-quantec-prime/model-slug/
            $customRules[
                '^' . $prefix . $base . '/' . $reserved . '(?:[^/]+/)+([^/]+)/?$'
            ] = $queryPrefix;

            // Legacy / fallback short URL. WordPress can canonical-redirect it
            // to the hierarchy-aware permalink generated by filterLink().
            $customRules[
                '^' . $prefix . $base . '/' . $reserved . '([^/]+)/?$'
            ] = $queryPrefix;
        }

        return $customRules + $rules;
    }

    public function maybeFlush(): void
    {
        if ((string) get_option(self::OPTION, '') === self::REWRITE_VERSION) {
            return;
        }

        flush_rewrite_rules(false);
        update_option(self::OPTION, self::REWRITE_VERSION, false);
    }

    private function archiveSlug(): string
    {
        $postType = get_post_type_object(ContentTypes::POST_TYPE);
        if (is_object($postType)) {
            if (is_string($postType->has_archive) && $postType->has_archive !== '') {
                return trim($postType->has_archive, '/');
            }
            if (is_array($postType->rewrite ?? null) && is_string($postType->rewrite['slug'] ?? null)) {
                return trim($postType->rewrite['slug'], '/');
            }
        }

        return 'robots/modeles';
    }

    /**
     * Return literal URL prefixes for the active Polylang URL configuration.
     *
     * A directory setup returns entries such as "fr" and "en". A language
     * configured on a separate domain has an empty path prefix; in that case a
     * single unprefixed rule is enough because Polylang resolves the language
     * from the host.
     *
     * @return array<int,array{prefix:string,language:string}>
     */
    private function localizedPrefixes(): array
    {
        if (!function_exists('pll_languages_list') || !function_exists('pll_home_url')) {
            return [['prefix' => '', 'language' => '']];
        }

        $languages = pll_languages_list(['fields' => 'slug']);
        if (!is_array($languages) || $languages === []) {
            return [['prefix' => '', 'language' => '']];
        }

        $homePath = (string) (wp_parse_url(home_url('/'), PHP_URL_PATH) ?? '/');
        $homePath = trim($homePath, '/');
        $homePath = $homePath === '' ? '/' : '/' . $homePath . '/';
        $entries = [];

        foreach ($languages as $language) {
            if (!is_string($language) || $language === '') {
                continue;
            }

            $localizedHome = pll_home_url($language);
            if (!is_string($localizedHome) || $localizedHome === '') {
                continue;
            }

            $localizedPath = (string) (wp_parse_url($localizedHome, PHP_URL_PATH) ?? '/');
            $localizedPath = '/' . trim($localizedPath, '/') . '/';
            $relative = $localizedPath;

            if ($homePath !== '/' && str_starts_with($localizedPath, $homePath)) {
                $relative = substr($localizedPath, strlen($homePath));
            } elseif ($homePath === '/') {
                $relative = ltrim($localizedPath, '/');
            }

            $prefix = trim((string) $relative, '/');
            $key = $prefix === '' ? '__root__' : $prefix;

            // Multiple languages may use different domains with the same path.
            // The host is then the language discriminator; keep one root rule.
            if (!isset($entries[$key])) {
                $entries[$key] = [
                    'prefix' => $prefix,
                    'language' => $prefix !== '' ? $language : '',
                ];
            }
        }

        return $entries !== [] ? array_values($entries) : [['prefix' => '', 'language' => '']];
    }

    private function deepestFamily(int $postId): ?WP_Term
    {
        $terms = get_the_terms($postId, ContentTypes::FAMILY_TAXONOMY);
        if (!is_array($terms)) {
            return null;
        }
        $selected = null;
        $depth = -1;
        foreach ($terms as $term) {
            if (!$term instanceof WP_Term) {
                continue;
            }
            $current = count(get_ancestors($term->term_id, ContentTypes::FAMILY_TAXONOMY, 'taxonomy'));
            if ($current > $depth) {
                $selected = $term;
                $depth = $current;
            }
        }
        return $selected;
    }
}
